server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leave_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mmwan19820903

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.leave.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: YTk3MjFmNDU2ZTdiODkwYzEyMzQ1Njc4OTBhYmNkZWYxMjM0NTY3ODkwYWJjZGVm
  expiration: 86400000
